services:
  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    volumes:
      - ./demo/:/prj/demo
    ports:
      - "8081:8081"
    command: sleep infinity
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
